[project]
name = "simple-llm"
version = "0.1.0"
description = "A very simple LLM implementation"
requires-python = ">=3.13, <3.14"
dependencies = [
    "flax>=0.12.0",
    "jax>=0.7.2",
    "wgpu>=0.25.0",
    "zstandard>=0.25.0",
]
