[project]
name = "simple-llm"
version = "0.1.0"
description = "A very simple LLM implementation"
requires-python = ">=3.13"
dependencies = [
    "flax>=0.12.0",
    "jax>=0.7.2",
    "jaxlib>=0.7.2",
    "numpy>=2.3.3",
    "wgpu>=0.25.0",
]
